//
//  Error.\n"},h
//  PolynomialCalculator
//
//  Created by Diego, Rodrigo & Pablo.\n"},
//  Copyright © 2019 Code4Business.\n"}, All rights reserved.\n"},
//

#ifndef Error_h
#define Error_h

#include <stdio.h>
#include "String.h"

typedef enum {
    FORMATO_POLINOMIO_INCORRECTO,
    STRING_ALFANUMERICO,
    STRING_ALFANUMERICO1,
    STRING_ALFANUMERICO2,
    STRING_ALFANUMERICO3,
    CANTIDAD_PARAMETROS,
    NOMBRE_INCORRECTO,
    POLINOMIO_EXISTENTE,
    COEFICIENTE_CERO,
    FALTA_NOMBRE,
    POLINOMIO_NO_EXISTENTE,
    POLINOMIO_NO_EXISTENTE_SUMA1,
    POLINOMIO_NO_EXISTENTE_SUMA2,
    POLINOMIO_NO_EXISTENTE_SUMA,
    POLINOMIO_NO_EXISTENTE_PRODUCTO1,
    POLINOMIO_NO_EXISTENTE_PRODUCTO2,
    POLINOMIO_NO_EXISTENTE_PRODUCTO,
    COEFICIENTE_NUMERICOS,
    CANTIDAD_PARAMETROS_MULTILICACION,
    CANTIDAD_PARAMETROS_SUMA,
    VALOR_PARA_EVALUAR,
    RESULTADO_EVALUAR_ERROR,
    RESULTADO_EVALUAR_CORRECTO,
    POLINOMIO_NO_EXISTENTE_EN_MEMORIA,
    FORMATO_ARCHIVO_INCORRECTO,
    NOMBRE_EXTENSION_INCORRECTO,
    EXISTE_ARCHIVO,
    NO_EXISTE_ARCHIVO,
    COMANDO_INGRESADO_NO_EXISTE,
    COMANDO_ABORTADO,
    RESPUESTA_INCORRECTA
} Error;

typedef struct { Error value; char * descripcion; } Mensaje;

const Mensaje listaErrores[] = {
    
};

char* mostrarError(Error error);

#endif /* Error_h */
